//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConferenceSpeakers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConferenceSpeakers()
        {
            this.ConferenceEvaluationSpeakers = new HashSet<ConferenceEvaluationSpeakers>();
            this.ConferenceSpeakerChecklists = new HashSet<ConferenceSpeakerChecklists>();
            this.ConferenceSpeakerTopics = new HashSet<ConferenceSpeakerTopics>();
            this.ConferencePanels = new HashSet<ConferencePanels>();
        }
    
        public int ID { get; set; }
        public int ConferenceID { get; set; }
        public string UserID { get; set; }
        public Nullable<decimal> SpeakerHours { get; set; }
        public Nullable<System.DateTime> SpeakerHoursAssignedOn { get; set; }
        public string SpeakerHoursAssignedBy { get; set; }
        public Nullable<System.DateTime> SpeakerHoursLastUpdatedOn { get; set; }
        public string SpeakerHoursLastUpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> FacultyDisclosureLastSent { get; set; }
        public bool FacultyDisclosureOnFile { get; set; }
        public Nullable<int> FacultyDisclosureID { get; set; }
        public Nullable<System.DateTime> SpeakerCheckListLastSent { get; set; }
        public bool SpeakerCheckListOnFile { get; set; }
        public Nullable<int> SpeakercheckListID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceEvaluationSpeakers> ConferenceEvaluationSpeakers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceSpeakerChecklists> ConferenceSpeakerChecklists { get; set; }
        public virtual UserProfiles UserProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceSpeakerTopics> ConferenceSpeakerTopics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferencePanels> ConferencePanels { get; set; }
    }
}
