//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConferenceCreditImports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConferenceCreditImports()
        {
            this.ConferenceCreditImportErrors = new HashSet<ConferenceCreditImportErrors>();
            this.ConferenceCreditImportRecords = new HashSet<ConferenceCreditImportRecords>();
        }
    
        public int ID { get; set; }
        public int ConferenceID { get; set; }
        public string FileLocation { get; set; }
        public string UserID { get; set; }
        public bool CreditNotificationsEnabled { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceCreditImportErrors> ConferenceCreditImportErrors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceCreditImportRecords> ConferenceCreditImportRecords { get; set; }
        public virtual UserProfiles UserProfiles { get; set; }
    }
}
