//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConferenceEvaluations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConferenceEvaluations()
        {
            this.ConferenceEvaluationCompetencies = new HashSet<ConferenceEvaluationCompetencies>();
            this.ConferenceEvaluationPanels = new HashSet<ConferenceEvaluationPanels>();
            this.ConferenceEvaluationProgramResults = new HashSet<ConferenceEvaluationProgramResults>();
            this.ConferenceEvaluationSpeakers = new HashSet<ConferenceEvaluationSpeakers>();
        }
    
        public int ID { get; set; }
        public string UserID { get; set; }
        public int ConferenceID { get; set; }
        public string ReferralSource { get; set; }
        public bool WillYouMakeChanges { get; set; }
        public string WillYouMakeChangesComments { get; set; }
        public string AdditionalComments { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public bool IsDeleted { get; set; }
        public string ReferralSourceOther { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceEvaluationCompetencies> ConferenceEvaluationCompetencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceEvaluationPanels> ConferenceEvaluationPanels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceEvaluationProgramResults> ConferenceEvaluationProgramResults { get; set; }
        public virtual UserProfiles UserProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceEvaluationSpeakers> ConferenceEvaluationSpeakers { get; set; }
    }
}
