//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditNotifications
    {
        public int ID { get; set; }
        public int EventID { get; set; }
        public string EventType { get; set; }
        public string UserID { get; set; }
        public System.DateTime SentOn { get; set; }
        public string SentBy { get; set; }
    
        public virtual EventTypes EventTypes { get; set; }
    }
}
