//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criteria23
    {
        public int ID { get; set; }
        public int EventID { get; set; }
        public string ActivityTitle { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public string ActivityFormat { get; set; }
        public string PlannerProfessions { get; set; }
        public string FacultyProfessions { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public string EventType { get; set; }
    }
}
