//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuplicateUserRuns
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DuplicateUserRuns()
        {
            this.DuplicateUserRunRecords = new HashSet<DuplicateUserRunRecords>();
        }
    
        public int ID { get; set; }
        public System.DateTime DuplicateRunTime { get; set; }
        public string UserID { get; set; }
        public bool IsComplete { get; set; }
        public Nullable<int> Records { get; set; }
        public Nullable<int> Completed { get; set; }
        public Nullable<System.DateTime> StartTimeStamp { get; set; }
        public Nullable<System.DateTime> EndTimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DuplicateUserRunRecords> DuplicateUserRunRecords { get; set; }
        public virtual UserProfiles UserProfiles { get; set; }
    }
}
