//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnduringMaterialSpeakers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnduringMaterialSpeakers()
        {
            this.EnduringMaterialEvaluationSpeakers = new HashSet<EnduringMaterialEvaluationSpeakers>();
            this.EnduringMaterialSpeakerChecklists = new HashSet<EnduringMaterialSpeakerChecklists>();
            this.EnduringMaterialSpeakerConsentForms = new HashSet<EnduringMaterialSpeakerConsentForms>();
            this.EnduringMaterialSpeakerTopics = new HashSet<EnduringMaterialSpeakerTopics>();
            this.EnduringMaterialPanels = new HashSet<EnduringMaterialPanels>();
        }
    
        public int ID { get; set; }
        public int EnduringMaterialID { get; set; }
        public string UserID { get; set; }
        public Nullable<decimal> SpeakerHours { get; set; }
        public Nullable<System.DateTime> SpeakerHoursAssignedOn { get; set; }
        public string SpeakerHoursAssignedBy { get; set; }
        public Nullable<System.DateTime> SpeakerHoursLastUpdatedOn { get; set; }
        public string SpeakerHoursLastUpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> FacultyDisclosureLastSent { get; set; }
        public bool FacultyDisclosureOnFile { get; set; }
        public Nullable<int> FacultyDisclosureID { get; set; }
        public Nullable<System.DateTime> SpeakerCheckListLastSent { get; set; }
        public bool SpeakerCheckListOnFile { get; set; }
        public Nullable<int> SpeakercheckListID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnduringMaterialEvaluationSpeakers> EnduringMaterialEvaluationSpeakers { get; set; }
        public virtual EnduringMaterials EnduringMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnduringMaterialSpeakerChecklists> EnduringMaterialSpeakerChecklists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnduringMaterialSpeakerConsentForms> EnduringMaterialSpeakerConsentForms { get; set; }
        public virtual UserProfiles UserProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnduringMaterialSpeakerTopics> EnduringMaterialSpeakerTopics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnduringMaterialPanels> EnduringMaterialPanels { get; set; }
    }
}
