//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnduringMaterialRegistrationItems
    {
        public int ID { get; set; }
        public int EnduringMaterialRegistrationID { get; set; }
        public string Type { get; set; }
        public Nullable<int> PriceID { get; set; }
        public Nullable<int> OptionID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
    
        public virtual EnduringMaterialOptions EnduringMaterialOptions { get; set; }
        public virtual EnduringMaterialPrices EnduringMaterialPrices { get; set; }
        public virtual EnduringMaterialRegistrations EnduringMaterialRegistrations { get; set; }
    }
}
