//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventPromoCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventPromoCode()
        {
            this.EventPromoCodeDegreeRestriction = new HashSet<EventPromoCodeDegreeRestriction>();
            this.EventPromoCodeEmailRestriction = new HashSet<EventPromoCodeEmailRestriction>();
            this.EventPromoCodeProfessionRestriction = new HashSet<EventPromoCodeProfessionRestriction>();
            this.ShoppingCartPromoCodes = new HashSet<ShoppingCartPromoCodes>();
        }
    
        public int ID { get; set; }
        public int EventID { get; set; }
        public string EventType { get; set; }
        public string Code { get; set; }
        public string Type { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsEmailRestricted { get; set; }
        public bool IsProfessionsRestricted { get; set; }
        public bool IsDegreesRestricted { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public string RestrictedEmails { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventPromoCodeDegreeRestriction> EventPromoCodeDegreeRestriction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventPromoCodeEmailRestriction> EventPromoCodeEmailRestriction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventPromoCodeProfessionRestriction> EventPromoCodeProfessionRestriction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCartPromoCodes> ShoppingCartPromoCodes { get; set; }
    }
}
