//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewOSUCCMEEntities : DbContext
    {
        public NewOSUCCMEEntities()
            : base("name=NewOSUCCMEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Boards> Boards { get; set; }
        public virtual DbSet<ConferenceCreditImportErrors> ConferenceCreditImportErrors { get; set; }
        public virtual DbSet<ConferenceCreditImportRecords> ConferenceCreditImportRecords { get; set; }
        public virtual DbSet<ConferenceCreditImports> ConferenceCreditImports { get; set; }
        public virtual DbSet<ConferenceEvaluationCompetencies> ConferenceEvaluationCompetencies { get; set; }
        public virtual DbSet<ConferenceEvaluationPanels> ConferenceEvaluationPanels { get; set; }
        public virtual DbSet<ConferenceEvaluationProgramResults> ConferenceEvaluationProgramResults { get; set; }
        public virtual DbSet<ConferenceEvaluations> ConferenceEvaluations { get; set; }
        public virtual DbSet<ConferenceEvaluationSpeakers> ConferenceEvaluationSpeakers { get; set; }
        public virtual DbSet<ConferenceFiles> ConferenceFiles { get; set; }
        public virtual DbSet<ConferenceJointProviders> ConferenceJointProviders { get; set; }
        public virtual DbSet<ConferenceNotes> ConferenceNotes { get; set; }
        public virtual DbSet<ConferenceOptions> ConferenceOptions { get; set; }
        public virtual DbSet<ConferenceOptionsGroups> ConferenceOptionsGroups { get; set; }
        public virtual DbSet<ConferencePanels> ConferencePanels { get; set; }
        public virtual DbSet<ConferencePrices> ConferencePrices { get; set; }
        public virtual DbSet<ConferenceQuestions> ConferenceQuestions { get; set; }
        public virtual DbSet<ConferenceRegistrationItems> ConferenceRegistrationItems { get; set; }
        public virtual DbSet<ConferenceRegistrations> ConferenceRegistrations { get; set; }
        public virtual DbSet<Conferences> Conferences { get; set; }
        public virtual DbSet<ConferenceSpeakerChecklistAVNeeds> ConferenceSpeakerChecklistAVNeeds { get; set; }
        public virtual DbSet<ConferenceSpeakerChecklistCVs> ConferenceSpeakerChecklistCVs { get; set; }
        public virtual DbSet<ConferenceSpeakerChecklistPresentationFiles> ConferenceSpeakerChecklistPresentationFiles { get; set; }
        public virtual DbSet<ConferenceSpeakerChecklists> ConferenceSpeakerChecklists { get; set; }
        public virtual DbSet<ConferenceSpeakers> ConferenceSpeakers { get; set; }
        public virtual DbSet<ConferenceSpeakerTopics> ConferenceSpeakerTopics { get; set; }
        public virtual DbSet<ConferenceSpecialties> ConferenceSpecialties { get; set; }
        public virtual DbSet<ConferenceStreams> ConferenceStreams { get; set; }
        public virtual DbSet<ConferenceStreamViews> ConferenceStreamViews { get; set; }
        public virtual DbSet<ConferenceViews> ConferenceViews { get; set; }
        public virtual DbSet<ConferenceWaitlist> ConferenceWaitlist { get; set; }
        public virtual DbSet<ConferenceWaitlistSettings> ConferenceWaitlistSettings { get; set; }
        public virtual DbSet<ContentManagementSystem> ContentManagementSystem { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Criteria> Criteria { get; set; }
        public virtual DbSet<Criteria23> Criteria23 { get; set; }
        public virtual DbSet<Criteria24> Criteria24 { get; set; }
        public virtual DbSet<Criteria25> Criteria25 { get; set; }
        public virtual DbSet<Criteria27> Criteria27 { get; set; }
        public virtual DbSet<Criteria28> Criteria28 { get; set; }
        public virtual DbSet<Criteria30> Criteria30 { get; set; }
        public virtual DbSet<Criteria32> Criteria32 { get; set; }
        public virtual DbSet<Criteria35> Criteria35 { get; set; }
        public virtual DbSet<Criteria37> Criteria37 { get; set; }
        public virtual DbSet<DegreeMapping> DegreeMapping { get; set; }
        public virtual DbSet<Degrees> Degrees { get; set; }
        public virtual DbSet<DuplicateUserRunIgnoreRecords> DuplicateUserRunIgnoreRecords { get; set; }
        public virtual DbSet<DuplicateUserRunRecords> DuplicateUserRunRecords { get; set; }
        public virtual DbSet<DuplicateUserRuns> DuplicateUserRuns { get; set; }
        public virtual DbSet<EmailHistory> EmailHistory { get; set; }
        public virtual DbSet<EmailPreferences> EmailPreferences { get; set; }
        public virtual DbSet<EmailQueueMessages> EmailQueueMessages { get; set; }
        public virtual DbSet<EmailQueues> EmailQueues { get; set; }
        public virtual DbSet<EmailTypes> EmailTypes { get; set; }
        public virtual DbSet<EnduringMaterialBoards> EnduringMaterialBoards { get; set; }
        public virtual DbSet<EnduringMaterialCreditImportErrors> EnduringMaterialCreditImportErrors { get; set; }
        public virtual DbSet<EnduringMaterialCreditImportRecords> EnduringMaterialCreditImportRecords { get; set; }
        public virtual DbSet<EnduringMaterialCreditImports> EnduringMaterialCreditImports { get; set; }
        public virtual DbSet<EnduringMaterialEvaluationCompetencies> EnduringMaterialEvaluationCompetencies { get; set; }
        public virtual DbSet<EnduringMaterialEvaluationPanels> EnduringMaterialEvaluationPanels { get; set; }
        public virtual DbSet<EnduringMaterialEvaluationProgramResults> EnduringMaterialEvaluationProgramResults { get; set; }
        public virtual DbSet<EnduringMaterialEvaluations> EnduringMaterialEvaluations { get; set; }
        public virtual DbSet<EnduringMaterialEvaluationSpeakers> EnduringMaterialEvaluationSpeakers { get; set; }
        public virtual DbSet<EnduringMaterialFiles> EnduringMaterialFiles { get; set; }
        public virtual DbSet<EnduringMaterialJointProviders> EnduringMaterialJointProviders { get; set; }
        public virtual DbSet<EnduringMaterialNotes> EnduringMaterialNotes { get; set; }
        public virtual DbSet<EnduringMaterialOptions> EnduringMaterialOptions { get; set; }
        public virtual DbSet<EnduringMaterialOptionsGroups> EnduringMaterialOptionsGroups { get; set; }
        public virtual DbSet<EnduringMaterialPanels> EnduringMaterialPanels { get; set; }
        public virtual DbSet<EnduringMaterialPrices> EnduringMaterialPrices { get; set; }
        public virtual DbSet<EnduringMaterialRegistrationItems> EnduringMaterialRegistrationItems { get; set; }
        public virtual DbSet<EnduringMaterialRegistrations> EnduringMaterialRegistrations { get; set; }
        public virtual DbSet<EnduringMaterials> EnduringMaterials { get; set; }
        public virtual DbSet<EnduringMaterialSeries> EnduringMaterialSeries { get; set; }
        public virtual DbSet<EnduringMaterialSpeakerChecklistCVs> EnduringMaterialSpeakerChecklistCVs { get; set; }
        public virtual DbSet<EnduringMaterialSpeakerChecklistPresentationFiles> EnduringMaterialSpeakerChecklistPresentationFiles { get; set; }
        public virtual DbSet<EnduringMaterialSpeakerChecklists> EnduringMaterialSpeakerChecklists { get; set; }
        public virtual DbSet<EnduringMaterialSpeakerConsentForms> EnduringMaterialSpeakerConsentForms { get; set; }
        public virtual DbSet<EnduringMaterialSpeakers> EnduringMaterialSpeakers { get; set; }
        public virtual DbSet<EnduringMaterialSpeakerTopics> EnduringMaterialSpeakerTopics { get; set; }
        public virtual DbSet<EnduringMaterialSpecialties> EnduringMaterialSpecialties { get; set; }
        public virtual DbSet<EnduringMaterialViews> EnduringMaterialViews { get; set; }
        public virtual DbSet<ErrorLog> ErrorLog { get; set; }
        public virtual DbSet<EventAdvertisers> EventAdvertisers { get; set; }
        public virtual DbSet<EventExpenses> EventExpenses { get; set; }
        public virtual DbSet<EventPromoCode> EventPromoCode { get; set; }
        public virtual DbSet<EventPromoCodeDegreeRestriction> EventPromoCodeDegreeRestriction { get; set; }
        public virtual DbSet<EventPromoCodeEmailRestriction> EventPromoCodeEmailRestriction { get; set; }
        public virtual DbSet<EventPromoCodeProfessionRestriction> EventPromoCodeProfessionRestriction { get; set; }
        public virtual DbSet<EventProvidership> EventProvidership { get; set; }
        public virtual DbSet<EventRevenues> EventRevenues { get; set; }
        public virtual DbSet<EventStatus> EventStatus { get; set; }
        public virtual DbSet<EventSupport> EventSupport { get; set; }
        public virtual DbSet<EventTypes> EventTypes { get; set; }
        public virtual DbSet<FacultyDisclosureCommercialInterests> FacultyDisclosureCommercialInterests { get; set; }
        public virtual DbSet<FacultyDisclosureRoles> FacultyDisclosureRoles { get; set; }
        public virtual DbSet<FacultyDisclosures> FacultyDisclosures { get; set; }
        public virtual DbSet<HospitalAdmins> HospitalAdmins { get; set; }
        public virtual DbSet<HospitalDocuments> HospitalDocuments { get; set; }
        public virtual DbSet<HospitalGroups> HospitalGroups { get; set; }
        public virtual DbSet<Hospitals> Hospitals { get; set; }
        public virtual DbSet<HospitalUsers> HospitalUsers { get; set; }
        public virtual DbSet<LoginLog> LoginLog { get; set; }
        public virtual DbSet<MOCCreditTypes> MOCCreditTypes { get; set; }
        public virtual DbSet<NelnetTransactionLog> NelnetTransactionLog { get; set; }
        public virtual DbSet<PaymentHistory> PaymentHistory { get; set; }
        public virtual DbSet<PaymentMethods> PaymentMethods { get; set; }
        public virtual DbSet<ProfessionMapping> ProfessionMapping { get; set; }
        public virtual DbSet<Professions> Professions { get; set; }
        public virtual DbSet<RSSeries> RSSeries { get; set; }
        public virtual DbSet<RSSeriesCreditImportErrors> RSSeriesCreditImportErrors { get; set; }
        public virtual DbSet<RSSeriesCreditImportRecords> RSSeriesCreditImportRecords { get; set; }
        public virtual DbSet<RSSeriesCreditImports> RSSeriesCreditImports { get; set; }
        public virtual DbSet<RSSeriesEvaluationCompetencies> RSSeriesEvaluationCompetencies { get; set; }
        public virtual DbSet<RSSeriesEvaluationPanels> RSSeriesEvaluationPanels { get; set; }
        public virtual DbSet<RSSeriesEvaluationProgramResults> RSSeriesEvaluationProgramResults { get; set; }
        public virtual DbSet<RSSeriesEvaluations> RSSeriesEvaluations { get; set; }
        public virtual DbSet<RSSeriesEvaluationSpeakers> RSSeriesEvaluationSpeakers { get; set; }
        public virtual DbSet<RSSeriesFiles> RSSeriesFiles { get; set; }
        public virtual DbSet<RSSeriesJointProviders> RSSeriesJointProviders { get; set; }
        public virtual DbSet<RSSeriesNotes> RSSeriesNotes { get; set; }
        public virtual DbSet<RSSeriesPanels> RSSeriesPanels { get; set; }
        public virtual DbSet<RSSeriesRegistrations> RSSeriesRegistrations { get; set; }
        public virtual DbSet<RSSeriesSeries> RSSeriesSeries { get; set; }
        public virtual DbSet<RSSeriesSeriesAdmins> RSSeriesSeriesAdmins { get; set; }
        public virtual DbSet<RSSeriesSeriesNotes> RSSeriesSeriesNotes { get; set; }
        public virtual DbSet<RSSeriesSeriesYearlyInfo> RSSeriesSeriesYearlyInfo { get; set; }
        public virtual DbSet<RSSeriesSpeakerChecklistCVs> RSSeriesSpeakerChecklistCVs { get; set; }
        public virtual DbSet<RSSeriesSpeakerChecklistPresentationFiles> RSSeriesSpeakerChecklistPresentationFiles { get; set; }
        public virtual DbSet<RSSeriesSpeakerChecklists> RSSeriesSpeakerChecklists { get; set; }
        public virtual DbSet<RSSeriesSpeakers> RSSeriesSpeakers { get; set; }
        public virtual DbSet<RSSeriesSpeakerTopics> RSSeriesSpeakerTopics { get; set; }
        public virtual DbSet<RSSeriesSpecialties> RSSeriesSpecialties { get; set; }
        public virtual DbSet<RSSeriesStreams> RSSeriesStreams { get; set; }
        public virtual DbSet<RSSeriesStreamViews> RSSeriesStreamViews { get; set; }
        public virtual DbSet<RSSeriesViews> RSSeriesViews { get; set; }
        public virtual DbSet<ShoppingCart> ShoppingCart { get; set; }
        public virtual DbSet<ShoppingCartItems> ShoppingCartItems { get; set; }
        public virtual DbSet<ShoppingCartOptions> ShoppingCartOptions { get; set; }
        public virtual DbSet<ShoppingCartPromoCodes> ShoppingCartPromoCodes { get; set; }
        public virtual DbSet<SingleSignOnTokens> SingleSignOnTokens { get; set; }
        public virtual DbSet<Specialties> Specialties { get; set; }
        public virtual DbSet<SpecialtyMapping> SpecialtyMapping { get; set; }
        public virtual DbSet<SubSpecialties> SubSpecialties { get; set; }
        public virtual DbSet<Testing> Testing { get; set; }
        public virtual DbSet<TestingQuestions> TestingQuestions { get; set; }
        public virtual DbSet<TestingQuestionsAnswers> TestingQuestionsAnswers { get; set; }
        public virtual DbSet<TestingQuestionsFiles> TestingQuestionsFiles { get; set; }
        public virtual DbSet<TestingQuestionsTypes> TestingQuestionsTypes { get; set; }
        public virtual DbSet<TitleMapping> TitleMapping { get; set; }
        public virtual DbSet<Titles> Titles { get; set; }
        public virtual DbSet<UploadedFiles> UploadedFiles { get; set; }
        public virtual DbSet<UploadedImages> UploadedImages { get; set; }
        public virtual DbSet<UserBoardIdentificationNumbers> UserBoardIdentificationNumbers { get; set; }
        public virtual DbSet<UserIDMapping> UserIDMapping { get; set; }
        public virtual DbSet<UserImportErrors> UserImportErrors { get; set; }
        public virtual DbSet<UserImportRecords> UserImportRecords { get; set; }
        public virtual DbSet<UserImports> UserImports { get; set; }
        public virtual DbSet<UserNotes> UserNotes { get; set; }
        public virtual DbSet<UserProfiles> UserProfiles { get; set; }
        public virtual DbSet<UserTestQuestionAnswers> UserTestQuestionAnswers { get; set; }
        public virtual DbSet<UserTestQuestions> UserTestQuestions { get; set; }
        public virtual DbSet<UserTests> UserTests { get; set; }
        public virtual DbSet<WebcastACCMEIDs> WebcastACCMEIDs { get; set; }
        public virtual DbSet<WebcastBoards> WebcastBoards { get; set; }
        public virtual DbSet<WebcastCreditImportErrors> WebcastCreditImportErrors { get; set; }
        public virtual DbSet<WebcastCreditImportRecords> WebcastCreditImportRecords { get; set; }
        public virtual DbSet<WebcastCreditImports> WebcastCreditImports { get; set; }
        public virtual DbSet<WebcastEvaluationCompetencies> WebcastEvaluationCompetencies { get; set; }
        public virtual DbSet<WebcastEvaluationPanels> WebcastEvaluationPanels { get; set; }
        public virtual DbSet<WebcastEvaluationProgramResults> WebcastEvaluationProgramResults { get; set; }
        public virtual DbSet<WebcastEvaluations> WebcastEvaluations { get; set; }
        public virtual DbSet<WebcastEvaluationSpeakers> WebcastEvaluationSpeakers { get; set; }
        public virtual DbSet<WebcastFiles> WebcastFiles { get; set; }
        public virtual DbSet<WebcastJointProviders> WebcastJointProviders { get; set; }
        public virtual DbSet<WebcastMOC> WebcastMOC { get; set; }
        public virtual DbSet<WebcastMOCCreditTypes> WebcastMOCCreditTypes { get; set; }
        public virtual DbSet<WebcastNotes> WebcastNotes { get; set; }
        public virtual DbSet<WebcastOptions> WebcastOptions { get; set; }
        public virtual DbSet<WebcastOptionsGroups> WebcastOptionsGroups { get; set; }
        public virtual DbSet<WebcastPanels> WebcastPanels { get; set; }
        public virtual DbSet<WebcastPrices> WebcastPrices { get; set; }
        public virtual DbSet<WebcastQuestions> WebcastQuestions { get; set; }
        public virtual DbSet<WebcastRegistrationItems> WebcastRegistrationItems { get; set; }
        public virtual DbSet<WebcastRegistrations> WebcastRegistrations { get; set; }
        public virtual DbSet<Webcasts> Webcasts { get; set; }
        public virtual DbSet<WebcastSpeakerChecklistAVNeeds> WebcastSpeakerChecklistAVNeeds { get; set; }
        public virtual DbSet<WebcastSpeakerChecklistCVs> WebcastSpeakerChecklistCVs { get; set; }
        public virtual DbSet<WebcastSpeakerChecklistPresentationFiles> WebcastSpeakerChecklistPresentationFiles { get; set; }
        public virtual DbSet<WebcastSpeakerChecklists> WebcastSpeakerChecklists { get; set; }
        public virtual DbSet<WebcastSpeakerConsentForms> WebcastSpeakerConsentForms { get; set; }
        public virtual DbSet<WebcastSpeakers> WebcastSpeakers { get; set; }
        public virtual DbSet<WebcastSpeakerTopics> WebcastSpeakerTopics { get; set; }
        public virtual DbSet<WebcastSpecialties> WebcastSpecialties { get; set; }
        public virtual DbSet<WebcastsViews> WebcastsViews { get; set; }
        public virtual DbSet<WebcastTest> WebcastTest { get; set; }
        public virtual DbSet<WebcastViews> WebcastViews { get; set; }
        public virtual DbSet<AggregatedCounter> AggregatedCounter { get; set; }
        public virtual DbSet<Counter> Counter { get; set; }
        public virtual DbSet<Hash> Hash { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<JobParameter> JobParameter { get; set; }
        public virtual DbSet<JobQueue> JobQueue { get; set; }
        public virtual DbSet<List> List { get; set; }
        public virtual DbSet<Schema> Schema { get; set; }
        public virtual DbSet<Server> Server { get; set; }
        public virtual DbSet<Set> Set { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<CreditNotifications> CreditNotifications { get; set; }
        public virtual DbSet<EmailFrequencies> EmailFrequencies { get; set; }
        public virtual DbSet<CategoryMapping> CategoryMapping { get; set; }
    }
}
