//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSSeriesSpeakers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RSSeriesSpeakers()
        {
            this.RSSeriesEvaluationSpeakers = new HashSet<RSSeriesEvaluationSpeakers>();
            this.RSSeriesSpeakerChecklists = new HashSet<RSSeriesSpeakerChecklists>();
            this.RSSeriesSpeakerTopics = new HashSet<RSSeriesSpeakerTopics>();
            this.RSSeriesPanels = new HashSet<RSSeriesPanels>();
        }
    
        public int ID { get; set; }
        public int RSSeriesID { get; set; }
        public string UserID { get; set; }
        public Nullable<decimal> SpeakerHours { get; set; }
        public Nullable<System.DateTime> SpeakerHoursAssignedOn { get; set; }
        public string SpeakerHoursAssignedBy { get; set; }
        public Nullable<System.DateTime> SpeakerHoursLastUpdatedOn { get; set; }
        public string SpeakerHoursLastUpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> FacultyDisclosureLastSent { get; set; }
        public bool FacultyDisclosureOnFile { get; set; }
        public Nullable<int> FacultyDisclosureID { get; set; }
        public Nullable<System.DateTime> SpeakerCheckListLastSent { get; set; }
        public bool SpeakerCheckListOnFile { get; set; }
        public Nullable<int> SpeakercheckListID { get; set; }
    
        public virtual RSSeries RSSeries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSSeriesEvaluationSpeakers> RSSeriesEvaluationSpeakers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSSeriesSpeakerChecklists> RSSeriesSpeakerChecklists { get; set; }
        public virtual UserProfiles UserProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSSeriesSpeakerTopics> RSSeriesSpeakerTopics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSSeriesPanels> RSSeriesPanels { get; set; }
    }
}
