//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSSeriesViews
    {
        public int ID { get; set; }
        public int RSSeriesID { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual RSSeries RSSeries { get; set; }
    }
}
