//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSSeriesSeriesYearlyInfo
    {
        public int ID { get; set; }
        public int SeriesID { get; set; }
        public int Year { get; set; }
        public string ActivityID { get; set; }
        public Nullable<bool> IsMOCEligible { get; set; }
        public string MOCReviewers { get; set; }
        public string Frequency { get; set; }
    
        public virtual RSSeriesSeries RSSeriesSeries { get; set; }
    }
}
