//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCartPromoCodes
    {
        public int ID { get; set; }
        public int ShoppingCartID { get; set; }
        public int PromoCodeID { get; set; }
        public int CartItemID { get; set; }
        public int EventID { get; set; }
        public string EventType { get; set; }
        public string Code { get; set; }
        public string Type { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
    
        public virtual EventPromoCode EventPromoCode { get; set; }
        public virtual ShoppingCart ShoppingCart { get; set; }
        public virtual ShoppingCartItems ShoppingCartItems { get; set; }
    }
}
