//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCartItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShoppingCartItems()
        {
            this.ShoppingCartOptions = new HashSet<ShoppingCartOptions>();
            this.ShoppingCartPromoCodes = new HashSet<ShoppingCartPromoCodes>();
        }
    
        public int ID { get; set; }
        public int ShoppingCartID { get; set; }
        public string ItemType { get; set; }
        public int EventID { get; set; }
        public int PriceID { get; set; }
        public decimal Price { get; set; }
        public string Tier { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ShoppingCart ShoppingCart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCartOptions> ShoppingCartOptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCartPromoCodes> ShoppingCartPromoCodes { get; set; }
    }
}
