//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfiles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserProfiles()
        {
            this.ConferenceCreditImports = new HashSet<ConferenceCreditImports>();
            this.ConferenceEvaluations = new HashSet<ConferenceEvaluations>();
            this.ConferenceNotes = new HashSet<ConferenceNotes>();
            this.ConferenceNotes1 = new HashSet<ConferenceNotes>();
            this.ConferenceRegistrations = new HashSet<ConferenceRegistrations>();
            this.ConferenceSpeakers = new HashSet<ConferenceSpeakers>();
            this.ConferenceStreamViews = new HashSet<ConferenceStreamViews>();
            this.ConferenceWaitlist = new HashSet<ConferenceWaitlist>();
            this.ContentManagementSystem = new HashSet<ContentManagementSystem>();
            this.DuplicateUserRunIgnoreRecords = new HashSet<DuplicateUserRunIgnoreRecords>();
            this.DuplicateUserRunRecords = new HashSet<DuplicateUserRunRecords>();
            this.DuplicateUserRunRecords1 = new HashSet<DuplicateUserRunRecords>();
            this.DuplicateUserRuns = new HashSet<DuplicateUserRuns>();
            this.EmailQueueMessages = new HashSet<EmailQueueMessages>();
            this.EnduringMaterialCreditImports = new HashSet<EnduringMaterialCreditImports>();
            this.EnduringMaterialEvaluations = new HashSet<EnduringMaterialEvaluations>();
            this.EnduringMaterialNotes = new HashSet<EnduringMaterialNotes>();
            this.EnduringMaterialNotes1 = new HashSet<EnduringMaterialNotes>();
            this.EnduringMaterialRegistrations = new HashSet<EnduringMaterialRegistrations>();
            this.EnduringMaterialSpeakers = new HashSet<EnduringMaterialSpeakers>();
            this.FacultyDisclosures = new HashSet<FacultyDisclosures>();
            this.HospitalAdmins = new HashSet<HospitalAdmins>();
            this.LoginLog = new HashSet<LoginLog>();
            this.RSSeriesCreditImports = new HashSet<RSSeriesCreditImports>();
            this.RSSeriesEvaluations = new HashSet<RSSeriesEvaluations>();
            this.RSSeriesNotes = new HashSet<RSSeriesNotes>();
            this.RSSeriesNotes1 = new HashSet<RSSeriesNotes>();
            this.RSSeriesRegistrations = new HashSet<RSSeriesRegistrations>();
            this.RSSeriesSeriesAdmins = new HashSet<RSSeriesSeriesAdmins>();
            this.RSSeriesSeriesNotes = new HashSet<RSSeriesSeriesNotes>();
            this.RSSeriesSeriesNotes1 = new HashSet<RSSeriesSeriesNotes>();
            this.RSSeriesSpeakers = new HashSet<RSSeriesSpeakers>();
            this.RSSeriesStreamViews = new HashSet<RSSeriesStreamViews>();
            this.ShoppingCart = new HashSet<ShoppingCart>();
            this.SingleSignOnTokens = new HashSet<SingleSignOnTokens>();
            this.UserBoardIdentificationNumbers = new HashSet<UserBoardIdentificationNumbers>();
            this.UserImports = new HashSet<UserImports>();
            this.UserNotes = new HashSet<UserNotes>();
            this.UserNotes1 = new HashSet<UserNotes>();
            this.UserNotes2 = new HashSet<UserNotes>();
            this.UserTests = new HashSet<UserTests>();
            this.WebcastCreditImports = new HashSet<WebcastCreditImports>();
            this.WebcastEvaluations = new HashSet<WebcastEvaluations>();
            this.WebcastNotes = new HashSet<WebcastNotes>();
            this.WebcastNotes1 = new HashSet<WebcastNotes>();
            this.WebcastRegistrations = new HashSet<WebcastRegistrations>();
            this.WebcastSpeakers = new HashSet<WebcastSpeakers>();
            this.WebcastsViews = new HashSet<WebcastsViews>();
        }
    
        public string UserID { get; set; }
        public string Email { get; set; }
        public int TitleID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public int ProfessionID { get; set; }
        public int DegreeID { get; set; }
        public string TraineeType { get; set; }
        public int SpecialtyID { get; set; }
        public Nullable<int> SubSpecialtyID { get; set; }
        public string Phone { get; set; }
        public string PhoneExtension { get; set; }
        public string Fax { get; set; }
        public string SpecialNeeds { get; set; }
        public string Department { get; set; }
        public string NameTag { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ProvinceRegion { get; set; }
        public string Country { get; set; }
        public string ZipCode { get; set; }
        public string PostalCode { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<System.DateTime> LastAccessedOn { get; set; }
        public Nullable<System.DateTime> EmailLastConfirmedOn { get; set; }
        public Nullable<System.DateTime> ArchivedOn { get; set; }
        public bool IsDeceased { get; set; }
        public bool IsDeleted { get; set; }
        public string OSUID { get; set; }
        public string NationalProviderIdentifier { get; set; }
        public bool AnnualFacultyDisclosureOverrideEnabled { get; set; }
        public Nullable<System.DateTime> AnnualFacultyDisclosureOverrideUpdatedOn { get; set; }
        public string AnnualFacultyDisclosureOverrideUpdatedBy { get; set; }
        public Nullable<bool> AnnualFacultyDisclosureAccess { get; set; }
        public Nullable<bool> IsBoardCertifiedPhysician { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string ABIMDiplomatNumber { get; set; }
        public Nullable<bool> HasAttested { get; set; }
        public Nullable<System.DateTime> ProfileUpdated { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceCreditImports> ConferenceCreditImports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceEvaluations> ConferenceEvaluations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceNotes> ConferenceNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceNotes> ConferenceNotes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceRegistrations> ConferenceRegistrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceSpeakers> ConferenceSpeakers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceStreamViews> ConferenceStreamViews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceWaitlist> ConferenceWaitlist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentManagementSystem> ContentManagementSystem { get; set; }
        public virtual Degrees Degrees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DuplicateUserRunIgnoreRecords> DuplicateUserRunIgnoreRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DuplicateUserRunRecords> DuplicateUserRunRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DuplicateUserRunRecords> DuplicateUserRunRecords1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DuplicateUserRuns> DuplicateUserRuns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailQueueMessages> EmailQueueMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnduringMaterialCreditImports> EnduringMaterialCreditImports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnduringMaterialEvaluations> EnduringMaterialEvaluations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnduringMaterialNotes> EnduringMaterialNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnduringMaterialNotes> EnduringMaterialNotes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnduringMaterialRegistrations> EnduringMaterialRegistrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnduringMaterialSpeakers> EnduringMaterialSpeakers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacultyDisclosures> FacultyDisclosures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalAdmins> HospitalAdmins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginLog> LoginLog { get; set; }
        public virtual Professions Professions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSSeriesCreditImports> RSSeriesCreditImports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSSeriesEvaluations> RSSeriesEvaluations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSSeriesNotes> RSSeriesNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSSeriesNotes> RSSeriesNotes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSSeriesRegistrations> RSSeriesRegistrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSSeriesSeriesAdmins> RSSeriesSeriesAdmins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSSeriesSeriesNotes> RSSeriesSeriesNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSSeriesSeriesNotes> RSSeriesSeriesNotes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSSeriesSpeakers> RSSeriesSpeakers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSSeriesStreamViews> RSSeriesStreamViews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart> ShoppingCart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SingleSignOnTokens> SingleSignOnTokens { get; set; }
        public virtual Specialties Specialties { get; set; }
        public virtual SubSpecialties SubSpecialties { get; set; }
        public virtual Titles Titles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBoardIdentificationNumbers> UserBoardIdentificationNumbers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserImports> UserImports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserNotes> UserNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserNotes> UserNotes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserNotes> UserNotes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTests> UserTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebcastCreditImports> WebcastCreditImports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebcastEvaluations> WebcastEvaluations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebcastNotes> WebcastNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebcastNotes> WebcastNotes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebcastRegistrations> WebcastRegistrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebcastSpeakers> WebcastSpeakers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebcastsViews> WebcastsViews { get; set; }
    }
}
