//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebcastEvaluationSpeakers
    {
        public int ID { get; set; }
        public int WebcastEvaluationID { get; set; }
        public int WebcastSpeakerID { get; set; }
        public string SpeakerName { get; set; }
        public string SpeakerTitle { get; set; }
        public int TopicID { get; set; }
        public string Topic { get; set; }
        public Nullable<int> PertinenceOfLecture { get; set; }
        public Nullable<int> EffectivenessOfPresentation { get; set; }
        public Nullable<int> UseOfAudioVisual { get; set; }
        public Nullable<int> ComprehensivenessOfMaterial { get; set; }
        public Nullable<bool> PresentationFreeOfCommercialBias { get; set; }
        public Nullable<int> NoCommercialBiasReason { get; set; }
    
        public virtual WebcastEvaluations WebcastEvaluations { get; set; }
        public virtual WebcastSpeakers WebcastSpeakers { get; set; }
    }
}
