//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebcastsViews
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public int WebcastID { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual UserProfiles UserProfiles { get; set; }
        public virtual Webcasts Webcasts { get; set; }
    }
}
