//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebcastSpeakerConsentForms
    {
        public int ID { get; set; }
        public int WebcastID { get; set; }
        public int WebcastSpeakerID { get; set; }
        public int WebcastSpeakerChecklistID { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public string Signature { get; set; }
        public System.DateTime SignatureDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Webcasts Webcasts { get; set; }
        public virtual WebcastSpeakerChecklists WebcastSpeakerChecklists { get; set; }
        public virtual WebcastSpeakers WebcastSpeakers { get; set; }
    }
}
