//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebcastTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebcastTest()
        {
            this.WebcastQuestions = new HashSet<WebcastQuestions>();
        }
    
        public int ID { get; set; }
        public int WebcastID { get; set; }
        public string TestType { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<double> PassingGrade { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> IsFree { get; set; }
        public Nullable<bool> IsOSUFree { get; set; }
        public Nullable<int> NumberOfTimesTaken { get; set; }
        public Nullable<bool> IsHospitalSubscriptionFree { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebcastQuestions> WebcastQuestions { get; set; }
    }
}
