//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldOSUDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactRequests
    {
        public int ID { get; set; }
        public string InquiryType { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Comments { get; set; }
        public System.DateTime DateSubmitted { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> FollowedUpWith { get; set; }
        public Nullable<System.DateTime> FollowedUpOn { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
