//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldOSUDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailQueue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmailQueue()
        {
            this.EmailQueueParameters = new HashSet<EmailQueueParameters>();
        }
    
        public int ID { get; set; }
        public string UserID { get; set; }
        public System.DateTime Date { get; set; }
        public int EmailQueueTypeID { get; set; }
        public bool IsDeleted { get; set; }
        public int WebcastID { get; set; }
        public Nullable<System.DateTime> SentOn { get; set; }
    
        public virtual EmailQueueType EmailQueueType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailQueueParameters> EmailQueueParameters { get; set; }
    }
}
