//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldOSUDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningFromTeachings
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string PhysicianName { get; set; }
        public string DatePublished { get; set; }
        public string TeachingActivityName { get; set; }
        public string Location { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Duration { get; set; }
        public Nullable<double> Credits { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> Completed { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public string UserID { get; set; }
        public string UserEmail { get; set; }
        public Nullable<int> CreditID { get; set; }
    }
}
