//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldOSUDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEvalAnswer
    {
        public int ID { get; set; }
        public Nullable<int> UserEvalID { get; set; }
        public Nullable<int> EvalQuestionID { get; set; }
        public string Answer { get; set; }
        public string Comment { get; set; }
    
        public virtual EvalQuestion EvalQuestion { get; set; }
        public virtual UserEval UserEval { get; set; }
    }
}
