//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldOSUDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Webcasts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Webcasts()
        {
            this.WebcastsACCMEIDs = new HashSet<WebcastsACCMEIDs>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Title { get; set; }
        public Nullable<bool> Live { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<bool> VODStatus { get; set; }
        public string VODURL { get; set; }
        public string LIVEURL { get; set; }
        public string Description { get; set; }
        public string Author { get; set; }
        public string Objectives { get; set; }
        public string Methodology { get; set; }
        public string CourseOutline { get; set; }
        public string TargetAudience { get; set; }
        public string TimeComplete { get; set; }
        public Nullable<decimal> Credits { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> PostTestNotification { get; set; }
        public string NotificationEmail { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<bool> Accredited { get; set; }
        public string ZIPURL { get; set; }
        public Nullable<bool> ToChangeCompetence { get; set; }
        public Nullable<bool> ToChangePerformance { get; set; }
        public Nullable<bool> ToChangePatientOutcomes { get; set; }
        public Nullable<bool> ActivityGoalsChangeCompetence { get; set; }
        public Nullable<bool> ActivityGoalsChangePerformance { get; set; }
        public Nullable<bool> ActivityGoalsChangePatientOutcomes { get; set; }
        public Nullable<bool> IsFacultyDevelopment { get; set; }
        public Nullable<bool> IsJointSponsor { get; set; }
        public string JointSponsor { get; set; }
        public Nullable<bool> OSUAffiliated { get; set; }
        public Nullable<bool> PublicViewable { get; set; }
        public bool SendCreditNotifications { get; set; }
        public Nullable<bool> ABMSPatientCareAndProceduralSkills { get; set; }
        public Nullable<bool> ABMSMedicalKnowledge { get; set; }
        public Nullable<bool> ABMSPracticeBasedLearningAndImprovement { get; set; }
        public Nullable<bool> ABMSInterpersonalAndCommunicationSkills { get; set; }
        public Nullable<bool> ABMSProfessionalism { get; set; }
        public Nullable<bool> ABMSSystemsBasedPractice { get; set; }
        public Nullable<bool> IOMProvidePatientCenteredCare { get; set; }
        public Nullable<bool> IOMWorkInInterdisciplinaryTeams { get; set; }
        public Nullable<bool> IOMEmployEvidenceBasedPractice { get; set; }
        public Nullable<bool> IOMApplyQualityImprovement { get; set; }
        public Nullable<bool> IOMUtilizeInformatics { get; set; }
        public Nullable<bool> IECValuesEthicsForInterprofessionalPractice { get; set; }
        public Nullable<bool> IECRolesResponsibilities { get; set; }
        public Nullable<bool> IECInterprofessionalCommunication { get; set; }
        public Nullable<bool> IECTeamsAndTeamwork { get; set; }
        public Nullable<bool> OCCompetenciesOtherThanThoseListedWereAddressed { get; set; }
        public Nullable<bool> IsMOC { get; set; }
        public string ACCMEActivityID { get; set; }
        public string PARsDescription { get; set; }
        public string FollowUp { get; set; }
        public string EmailContent { get; set; }
        public Nullable<bool> IsClone { get; set; }
        public Nullable<int> ClonedFromID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatingUserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebcastsACCMEIDs> WebcastsACCMEIDs { get; set; }
    }
}
