//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.OldModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OldConferenceStreamViews
    {
        public int ID { get; set; }
        public int ConferenceID { get; set; }
        public int ConferenceStreamID { get; set; }
        public string UserID { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual Conferences Conferences { get; set; }
        public virtual OldConferenceStreams OldConferenceStreams { get; set; }
    }
}
