//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.OldModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OldConferenceStreams
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OldConferenceStreams()
        {
            this.OldConferenceStreamViews = new HashSet<OldConferenceStreamViews>();
        }
    
        public int ID { get; set; }
        public int ConferenceID { get; set; }
        public string StreamTitle { get; set; }
        public string StreamDescription { get; set; }
        public string StreamURL { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Conferences Conferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OldConferenceStreamViews> OldConferenceStreamViews { get; set; }
    }
}
