//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.OldModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailQueueParameters
    {
        public int ID { get; set; }
        public int EmailQueueID { get; set; }
        public string Parameter { get; set; }
        public int Value { get; set; }
    
        public virtual EmailQueue EmailQueue { get; set; }
    }
}
