//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.OldModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnduringShoppingCarts
    {
        public int ID { get; set; }
        public string CartID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> EventID { get; set; }
        public string EventType { get; set; }
        public string Item { get; set; }
        public string Amount { get; set; }
        public Nullable<System.DateTime> CartDate { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
