//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.OldModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationsBackup
    {
        public int ID { get; set; }
        public string EventType { get; set; }
        public Nullable<int> EventID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> DropDown1 { get; set; }
        public string Comments1 { get; set; }
        public Nullable<int> DropDown2 { get; set; }
        public string Comments2 { get; set; }
        public Nullable<int> DropDown3 { get; set; }
        public string Comments3 { get; set; }
        public Nullable<int> DropDown4 { get; set; }
        public string Comments4 { get; set; }
        public Nullable<bool> RB5 { get; set; }
        public Nullable<bool> CommercialBias { get; set; }
        public Nullable<bool> AcademicBias { get; set; }
        public Nullable<bool> DisciplineBias { get; set; }
        public Nullable<bool> InstitutionalBias { get; set; }
        public Nullable<bool> ProceduralBias { get; set; }
        public Nullable<bool> OtherBias { get; set; }
        public string Comments5 { get; set; }
        public Nullable<int> DropDown6 { get; set; }
        public string Comments6 { get; set; }
        public string Comments7 { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
    }
}
