//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.OldModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectivesTestQuestions
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public string Presenter { get; set; }
        public string PresentatioinTitle { get; set; }
        public string Objective1 { get; set; }
        public string Objective2 { get; set; }
        public string Q1 { get; set; }
        public string Q2 { get; set; }
        public string Q3 { get; set; }
        public string Q4 { get; set; }
        public string Q5 { get; set; }
        public string Q6 { get; set; }
        public string Q7 { get; set; }
        public string Q8 { get; set; }
        public string Q9 { get; set; }
        public string Q10 { get; set; }
        public string A11 { get; set; }
        public string A12 { get; set; }
        public string A13 { get; set; }
        public string A14 { get; set; }
        public string A15 { get; set; }
        public string A21 { get; set; }
        public string A22 { get; set; }
        public string A23 { get; set; }
        public string A24 { get; set; }
        public string A25 { get; set; }
        public string A31 { get; set; }
        public string A32 { get; set; }
        public string A33 { get; set; }
        public string A34 { get; set; }
        public string A35 { get; set; }
        public string A41 { get; set; }
        public string A42 { get; set; }
        public string A43 { get; set; }
        public string A44 { get; set; }
        public string A45 { get; set; }
        public string A51 { get; set; }
        public string A52 { get; set; }
        public string A53 { get; set; }
        public string A54 { get; set; }
        public string A55 { get; set; }
        public string A61 { get; set; }
        public string A62 { get; set; }
        public string A63 { get; set; }
        public string A64 { get; set; }
        public string A65 { get; set; }
        public string A71 { get; set; }
        public string A72 { get; set; }
        public string A73 { get; set; }
        public string A74 { get; set; }
        public string A75 { get; set; }
        public string A81 { get; set; }
        public string A82 { get; set; }
        public string A83 { get; set; }
        public string A84 { get; set; }
        public string A85 { get; set; }
        public string A91 { get; set; }
        public string A92 { get; set; }
        public string A93 { get; set; }
        public string A94 { get; set; }
        public string A95 { get; set; }
        public string A101 { get; set; }
        public string A102 { get; set; }
        public string A103 { get; set; }
        public string A104 { get; set; }
        public string A105 { get; set; }
        public Nullable<bool> RB11 { get; set; }
        public Nullable<bool> RB12 { get; set; }
        public Nullable<bool> RB13 { get; set; }
        public Nullable<bool> RB14 { get; set; }
        public Nullable<bool> RB15 { get; set; }
        public Nullable<bool> RB21 { get; set; }
        public Nullable<bool> RB22 { get; set; }
        public Nullable<bool> RB23 { get; set; }
        public Nullable<bool> RB24 { get; set; }
        public Nullable<bool> RB25 { get; set; }
        public Nullable<bool> RB31 { get; set; }
        public Nullable<bool> RB32 { get; set; }
        public Nullable<bool> RB33 { get; set; }
        public Nullable<bool> RB34 { get; set; }
        public Nullable<bool> RB35 { get; set; }
        public Nullable<bool> RB41 { get; set; }
        public Nullable<bool> RB42 { get; set; }
        public Nullable<bool> RB43 { get; set; }
        public Nullable<bool> RB44 { get; set; }
        public Nullable<bool> RB45 { get; set; }
        public Nullable<bool> RB51 { get; set; }
        public Nullable<bool> RB52 { get; set; }
        public Nullable<bool> RB53 { get; set; }
        public Nullable<bool> RB54 { get; set; }
        public Nullable<bool> RB55 { get; set; }
        public Nullable<bool> RB61 { get; set; }
        public Nullable<bool> RB62 { get; set; }
        public Nullable<bool> RB63 { get; set; }
        public Nullable<bool> RB64 { get; set; }
        public Nullable<bool> RB65 { get; set; }
        public Nullable<bool> RB71 { get; set; }
        public Nullable<bool> RB72 { get; set; }
        public Nullable<bool> RB73 { get; set; }
        public Nullable<bool> RB74 { get; set; }
        public Nullable<bool> RB75 { get; set; }
        public Nullable<bool> RB81 { get; set; }
        public Nullable<bool> RB82 { get; set; }
        public Nullable<bool> RB83 { get; set; }
        public Nullable<bool> RB84 { get; set; }
        public Nullable<bool> RB85 { get; set; }
        public Nullable<bool> RB91 { get; set; }
        public Nullable<bool> RB92 { get; set; }
        public Nullable<bool> RB93 { get; set; }
        public Nullable<bool> RB94 { get; set; }
        public Nullable<bool> RB95 { get; set; }
        public Nullable<bool> RB101 { get; set; }
        public Nullable<bool> RB102 { get; set; }
        public Nullable<bool> RB103 { get; set; }
        public Nullable<bool> RB104 { get; set; }
        public Nullable<bool> RB105 { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> SumbitDate { get; set; }
        public string UserID { get; set; }
    }
}
