//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.OldModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersTest
    {
        public int ID { get; set; }
        public string TestApplicantID { get; set; }
        public Nullable<int> TestID { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public Nullable<double> Result { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<int> RegistrationID { get; set; }
        public Nullable<bool> PassedTest { get; set; }
    }
}
