//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.OldModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebcastPollAnswers
    {
        public int id { get; set; }
        public string UserID { get; set; }
        public Nullable<int> eventID { get; set; }
        public Nullable<int> PollID { get; set; }
        public Nullable<int> AnswerID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
    }
}
