//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.OldModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebcastPromoCodeRestrictedEmails
    {
        public int ID { get; set; }
        public int WebcastPromoCodeID { get; set; }
        public string Email { get; set; }
    
        public virtual WebcastPromoCodes WebcastPromoCodes { get; set; }
    }
}
