//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConferencePromoCodes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConferencePromoCodes()
        {
            this.ConferencePromoCodeDegrees = new HashSet<ConferencePromoCodeDegrees>();
            this.ConferencePromoCodeProfessions = new HashSet<ConferencePromoCodeProfessions>();
            this.ConferencePromoCodeRestrictedEmails = new HashSet<ConferencePromoCodeRestrictedEmails>();
        }
    
        public int ID { get; set; }
        public int ConferenceID { get; set; }
        public string Code { get; set; }
        public string Type { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsEmailRestricted { get; set; }
        public bool IsProfessionsRestricted { get; set; }
        public bool IsDegreesRestricted { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferencePromoCodeDegrees> ConferencePromoCodeDegrees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferencePromoCodeProfessions> ConferencePromoCodeProfessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferencePromoCodeRestrictedEmails> ConferencePromoCodeRestrictedEmails { get; set; }
    }
}
