//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConferenceExtras
    {
        public int ID { get; set; }
        public string ConferenceID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Price { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<int> GroupBy { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public Nullable<int> MaxAttendance { get; set; }
        public Nullable<int> Attendance { get; set; }
    }
}
