//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        public string Abbreviation { get; set; }
        public string Name { get; set; }
        public string UppercaseName { get; set; }
        public string AbbreviationThree { get; set; }
        public int NumberCode { get; set; }
        public int PhoneCode { get; set; }
    }
}
