//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criteria35
    {
        public int ID { get; set; }
        public int EventID { get; set; }
        public string EventType { get; set; }
        public string InnovationDescription1 { get; set; }
        public string InnovationDescription2 { get; set; }
        public string InnovationDescription3 { get; set; }
        public string InnovationDescription4 { get; set; }
        public bool IsDeleted { get; set; }
    }
}
