//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailHistory
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string Email { get; set; }
        public string EmailType { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string SentBy { get; set; }
        public string EmailMessage { get; set; }
    
        public virtual EmailTypes EmailTypes { get; set; }
    }
}
