//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnduringMaterials
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public string CreatingUserID { get; set; }
        public Nullable<double> Credits { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string EstimatedTimeToComplete { get; set; }
        public Nullable<bool> PublicViewable { get; set; }
        public string Price { get; set; }
        public Nullable<bool> ToChangeCompetence { get; set; }
        public Nullable<bool> ToChangePerformance { get; set; }
        public Nullable<bool> ToChangePatientOutcomes { get; set; }
        public Nullable<bool> ActivityGoalsChangeCompetence { get; set; }
        public Nullable<bool> ActivityGoalsChangePerformance { get; set; }
        public Nullable<bool> ActivityGoalsChangePatientOutcomes { get; set; }
        public Nullable<int> SeriesID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Objectives { get; set; }
        public Nullable<bool> IsFacultyDevelopment { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<bool> OSUAffiliated { get; set; }
        public Nullable<bool> isJointSponsor { get; set; }
        public string JointSponsor { get; set; }
        public Nullable<bool> Accredited { get; set; }
        public bool SendCreditNotifications { get; set; }
        public Nullable<bool> ABMSPatientCareAndProceduralSkills { get; set; }
        public Nullable<bool> ABMSMedicalKnowledge { get; set; }
        public Nullable<bool> ABMSPracticeBasedLearningAndImprovement { get; set; }
        public Nullable<bool> ABMSInterpersonalAndCommunicationSkills { get; set; }
        public Nullable<bool> ABMSProfessionalism { get; set; }
        public Nullable<bool> ABMSSystemsBasedPractice { get; set; }
        public Nullable<bool> IOMProvidePatientCenteredCare { get; set; }
        public Nullable<bool> IOMWorkInInterdisciplinaryTeams { get; set; }
        public Nullable<bool> IOMEmployEvidenceBasedPractice { get; set; }
        public Nullable<bool> IOMApplyQualityImprovement { get; set; }
        public Nullable<bool> IOMUtilizeInformatics { get; set; }
        public Nullable<bool> IECValuesEthicsForInterprofessionalPractice { get; set; }
        public Nullable<bool> IECRolesResponsibilities { get; set; }
        public Nullable<bool> IECInterprofessionalCommunication { get; set; }
        public Nullable<bool> IECTeamsAndTeamwork { get; set; }
        public Nullable<bool> OCCompetenciesOtherThanThoseListedWereAddressed { get; set; }
        public Nullable<bool> IsClone { get; set; }
        public Nullable<int> ClonedFromID { get; set; }
    }
}
