//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnduringMaterialCreditImports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnduringMaterialCreditImports()
        {
            this.EnduringMaterialCreditImportErrors = new HashSet<EnduringMaterialCreditImportErrors>();
            this.EnduringMaterialCreditImportRecords = new HashSet<EnduringMaterialCreditImportRecords>();
        }
    
        public int ID { get; set; }
        public int EnduringMaterialID { get; set; }
        public string FileLocation { get; set; }
        public string UserID { get; set; }
        public bool CreditNotificationsEnabled { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnduringMaterialCreditImportErrors> EnduringMaterialCreditImportErrors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnduringMaterialCreditImportRecords> EnduringMaterialCreditImportRecords { get; set; }
        public virtual EnduringMaterials EnduringMaterials { get; set; }
        public virtual UserProfiles UserProfiles { get; set; }
    }
}
