//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnduringMaterialSpeakerChecklists
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnduringMaterialSpeakerChecklists()
        {
            this.EnduringMaterialSpeakerChecklistCVs = new HashSet<EnduringMaterialSpeakerChecklistCVs>();
            this.EnduringMaterialSpeakerChecklistPresentationFiles = new HashSet<EnduringMaterialSpeakerChecklistPresentationFiles>();
            this.EnduringMaterialSpeakerConsentForms = new HashSet<EnduringMaterialSpeakerConsentForms>();
        }
    
        public int ID { get; set; }
        public string Type { get; set; }
        public int EnduringMaterialID { get; set; }
        public int EnduringMaterialSpeakerID { get; set; }
        public string ObjectivesStatus { get; set; }
        public string ObjectivesValue { get; set; }
        public string ReferencesStatus { get; set; }
        public string ReferencesValue { get; set; }
        public string CVStatus { get; set; }
        public string PresentationFilesStatus { get; set; }
        public string PresenterConsentFormStatus { get; set; }
        public bool ReceiveEvaluationSummary { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
    
        public virtual EnduringMaterials EnduringMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnduringMaterialSpeakerChecklistCVs> EnduringMaterialSpeakerChecklistCVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnduringMaterialSpeakerChecklistPresentationFiles> EnduringMaterialSpeakerChecklistPresentationFiles { get; set; }
        public virtual EnduringMaterialSpeakers EnduringMaterialSpeakers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnduringMaterialSpeakerConsentForms> EnduringMaterialSpeakerConsentForms { get; set; }
    }
}
