//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnduringMaterialSpeakerConsentForms
    {
        public int ID { get; set; }
        public int EnduringMaterialID { get; set; }
        public int EnduringMaterialSpeakerID { get; set; }
        public int EnduringMaterialSpeakerChecklistID { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public string Signature { get; set; }
        public System.DateTime SignatureDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual EnduringMaterials EnduringMaterials { get; set; }
        public virtual EnduringMaterialSpeakerChecklists EnduringMaterialSpeakerChecklists { get; set; }
        public virtual EnduringMaterialSpeakers EnduringMaterialSpeakers { get; set; }
    }
}
