//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluations
    {
        public int ID { get; set; }
        public string EventType { get; set; }
        public Nullable<int> EventID { get; set; }
        public string UserID { get; set; }
        public string rbl1 { get; set; }
        public string Comments1 { get; set; }
        public string rbl2 { get; set; }
        public string Comments2 { get; set; }
        public string rbl3 { get; set; }
        public string Comments3 { get; set; }
        public string rbl4 { get; set; }
        public string Comments4 { get; set; }
        public string rbl5 { get; set; }
        public string Comments5 { get; set; }
        public string rbl6 { get; set; }
        public string Comments6 { get; set; }
        public string rbl7 { get; set; }
        public string Comments7 { get; set; }
        public string rbl8 { get; set; }
        public string Comments8 { get; set; }
        public string rbl9 { get; set; }
        public string Comments9 { get; set; }
        public string rbl10 { get; set; }
        public string Comments10 { get; set; }
        public string rbl11 { get; set; }
        public string Comments11 { get; set; }
        public string rbl12 { get; set; }
        public string Comments12 { get; set; }
        public string rbl13 { get; set; }
        public string Comments13 { get; set; }
        public string rbl14 { get; set; }
        public string Comments14 { get; set; }
        public string rbl15 { get; set; }
        public string Comments15 { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
    }
}
