//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentHistory
    {
        public int ID { get; set; }
        public string EventType { get; set; }
        public int EventID { get; set; }
        public string OtherIdentifier { get; set; }
        public string PaymentType { get; set; }
        public decimal PaymentAmount { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string UserID { get; set; }
        public string OrderNumber { get; set; }
    }
}
