//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointOfCares
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ClinicalQuestion { get; set; }
        public string JournalName { get; set; }
        public string DatePublished { get; set; }
        public string ArticleTitle { get; set; }
        public string PageRange { get; set; }
        public string Author { get; set; }
        public string ClinicalApplication { get; set; }
        public string Reference { get; set; }
        public string Duration { get; set; }
        public Nullable<double> Credits { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> Completed { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
    }
}
