//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public int ID { get; set; }
        public Nullable<int> TestID { get; set; }
        public Nullable<int> Position { get; set; }
        public string QuestionText { get; set; }
        public Nullable<int> AnswerType { get; set; }
        public Nullable<int> MinAnsRequired { get; set; }
        public string CorrectAnswer { get; set; }
        public string AssociatedFileType { get; set; }
        public string AssociatedFileName { get; set; }
        public string AssociatedFileURL { get; set; }
        public string AnswerExplanation { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
