//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSSeriesCreditImports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RSSeriesCreditImports()
        {
            this.RSSeriesCreditImportErrors = new HashSet<RSSeriesCreditImportErrors>();
            this.RSSeriesCreditImportRecords = new HashSet<RSSeriesCreditImportRecords>();
        }
    
        public int ID { get; set; }
        public int RSSeriesID { get; set; }
        public string FileLocation { get; set; }
        public string UserID { get; set; }
        public bool CreditNotificationsEnabled { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual RSSeries RSSeries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSSeriesCreditImportErrors> RSSeriesCreditImportErrors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSSeriesCreditImportRecords> RSSeriesCreditImportRecords { get; set; }
        public virtual UserProfiles UserProfiles { get; set; }
    }
}
