//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSSeriesEvaluations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RSSeriesEvaluations()
        {
            this.RSSeriesEvaluationCompetencies = new HashSet<RSSeriesEvaluationCompetencies>();
            this.RSSeriesEvaluationPanels = new HashSet<RSSeriesEvaluationPanels>();
            this.RSSeriesEvaluationProgramResults = new HashSet<RSSeriesEvaluationProgramResults>();
            this.RSSeriesEvaluationSpeakers = new HashSet<RSSeriesEvaluationSpeakers>();
        }
    
        public int ID { get; set; }
        public string UserID { get; set; }
        public int RSSeriesID { get; set; }
        public string ReferralSource { get; set; }
        public bool WillYouMakeChanges { get; set; }
        public string WillYouMakeChangesComments { get; set; }
        public string AdditionalComments { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public bool IsDeleted { get; set; }
        public string ReferralSourceOther { get; set; }
    
        public virtual RSSeries RSSeries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSSeriesEvaluationCompetencies> RSSeriesEvaluationCompetencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSSeriesEvaluationPanels> RSSeriesEvaluationPanels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSSeriesEvaluationProgramResults> RSSeriesEvaluationProgramResults { get; set; }
        public virtual UserProfiles UserProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSSeriesEvaluationSpeakers> RSSeriesEvaluationSpeakers { get; set; }
    }
}
