//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSSeriesSpeakerChecklists
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RSSeriesSpeakerChecklists()
        {
            this.RSSeriesSpeakerChecklistCVs = new HashSet<RSSeriesSpeakerChecklistCVs>();
            this.RSSeriesSpeakerChecklistPresentationFiles = new HashSet<RSSeriesSpeakerChecklistPresentationFiles>();
        }
    
        public int ID { get; set; }
        public string Type { get; set; }
        public int RSSeriesID { get; set; }
        public int RSSeriesSpeakerID { get; set; }
        public string ObjectivesStatus { get; set; }
        public string ObjectivesValue { get; set; }
        public string ReferencesStatus { get; set; }
        public string ReferencesValue { get; set; }
        public string CVStatus { get; set; }
        public string PresentationFilesStatus { get; set; }
        public bool ReceiveEvaluationSummary { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
    
        public virtual RSSeries RSSeries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSSeriesSpeakerChecklistCVs> RSSeriesSpeakerChecklistCVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSSeriesSpeakerChecklistPresentationFiles> RSSeriesSpeakerChecklistPresentationFiles { get; set; }
        public virtual RSSeriesSpeakers RSSeriesSpeakers { get; set; }
    }
}
