//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSSeriesEvaluationPanels
    {
        public int ID { get; set; }
        public int RSSeriesEvaluationID { get; set; }
        public int RSSeriesPanelID { get; set; }
        public string RSSeriesPanelName { get; set; }
        public Nullable<int> PertinenceOfLecture { get; set; }
        public Nullable<int> EffectivenessOfPresentation { get; set; }
        public Nullable<int> UseOfAudioVisual { get; set; }
        public Nullable<int> ComprehensivenessOfMaterial { get; set; }
        public Nullable<bool> PresentationFreeOfCommercialBias { get; set; }
        public Nullable<int> NoCommercialBiasReason { get; set; }
    
        public virtual RSSeriesEvaluations RSSeriesEvaluations { get; set; }
        public virtual RSSeriesPanels RSSeriesPanels { get; set; }
    }
}
