//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyResultAnswers
    {
        public int ID { get; set; }
        public Nullable<int> SurveyResultID { get; set; }
        public Nullable<int> SurveyQuestionID { get; set; }
        public string Answer { get; set; }
    
        public virtual SurveyQuestions SurveyQuestions { get; set; }
        public virtual SurveyResult SurveyResult { get; set; }
    }
}
