//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testing
    {
        public int ID { get; set; }
        public string TestType { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> AssociatedEventID { get; set; }
        public string AssociatedEventType { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<double> PassingGrade { get; set; }
        public string Price { get; set; }
        public Nullable<bool> IsFree { get; set; }
        public Nullable<bool> IsOSUFree { get; set; }
        public Nullable<int> NumberOfTimesTaken { get; set; }
        public Nullable<bool> IsHospitalSubscriptionFree { get; set; }
    }
}
