//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEval
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserEval()
        {
            this.UserEvalAnswer = new HashSet<UserEvalAnswer>();
        }
    
        public int ID { get; set; }
        public Nullable<int> EventEvalID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> DateResponded { get; set; }
    
        public virtual EventEval EventEval { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserEvalAnswer> UserEvalAnswer { get; set; }
    }
}
