//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTests()
        {
            this.UserTestQuestions = new HashSet<UserTestQuestions>();
        }
    
        public int ID { get; set; }
        public int TestingID { get; set; }
        public string UserID { get; set; }
        public int EventID { get; set; }
        public string EventType { get; set; }
        public string TestType { get; set; }
        public string PaymentType { get; set; }
        public bool IsSubmitted { get; set; }
        public Nullable<System.DateTime> SubmittedOn { get; set; }
        public string SubmittedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public int TestPassingGrade { get; set; }
        public Nullable<int> Grade { get; set; }
        public Nullable<bool> IsPassed { get; set; }
    
        public virtual Testing Testing { get; set; }
        public virtual UserProfiles UserProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTestQuestions> UserTestQuestions { get; set; }
    }
}
