//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.ContactRequests = new HashSet<ContactRequests>();
            this.UnaffiliatedUsers = new HashSet<UnaffiliatedUsers>();
            this.UnaffiliatedUsers1 = new HashSet<UnaffiliatedUsers>();
        }
    
        public int ID { get; set; }
        public string UserID { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> PrefixID { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UserDegreeID { get; set; }
        public string MailingAddress1 { get; set; }
        public string MailingAddress2 { get; set; }
        public string MailingCity { get; set; }
        public string MailingState { get; set; }
        public string MailingZip { get; set; }
        public string MailingCountry { get; set; }
        public string BusinessPhone { get; set; }
        public string BusinessPhoneExtension { get; set; }
        public string FaxNumber { get; set; }
        public string SpecialNeeds { get; set; }
        public Nullable<int> ProfessionID { get; set; }
        public Nullable<int> SpecialtyID { get; set; }
        public Nullable<bool> PromoEmailOptIn { get; set; }
        public string Department { get; set; }
        public string NameTag { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> LastAccessed { get; set; }
        public Nullable<System.Guid> UniqueID { get; set; }
        public Nullable<bool> IsDeceased { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<bool> EmailUpdated { get; set; }
        public string FullName { get; set; }
        public string ABIMDiplomatNumber { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<bool> IsABIM { get; set; }
        public Nullable<bool> MOCAttestation { get; set; }
        public Nullable<System.DateTime> UpdateInformationTimeStamp { get; set; }
        public Nullable<bool> IsImport { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactRequests> ContactRequests { get; set; }
        public virtual Professions Professions { get; set; }
        public virtual Specialties Specialties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnaffiliatedUsers> UnaffiliatedUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnaffiliatedUsers> UnaffiliatedUsers1 { get; set; }
        public virtual UserDegrees UserDegrees { get; set; }
        public virtual UserPrefixes UserPrefixes { get; set; }
    }
}
