//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebcastSpeakerChecklists
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebcastSpeakerChecklists()
        {
            this.WebcastSpeakerChecklistAVNeeds = new HashSet<WebcastSpeakerChecklistAVNeeds>();
            this.WebcastSpeakerChecklistCVs = new HashSet<WebcastSpeakerChecklistCVs>();
            this.WebcastSpeakerChecklistPresentationFiles = new HashSet<WebcastSpeakerChecklistPresentationFiles>();
            this.WebcastSpeakerConsentForms = new HashSet<WebcastSpeakerConsentForms>();
        }
    
        public int ID { get; set; }
        public string Type { get; set; }
        public int WebcastID { get; set; }
        public int WebcastSpeakerID { get; set; }
        public string ObjectivesStatus { get; set; }
        public string ObjectivesValue { get; set; }
        public string ReferencesStatus { get; set; }
        public string ReferencesValue { get; set; }
        public string CVStatus { get; set; }
        public string PresentationFilesStatus { get; set; }
        public bool ReceiveEvaluationSummary { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public string PresenterConsentFormStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebcastSpeakerChecklistAVNeeds> WebcastSpeakerChecklistAVNeeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebcastSpeakerChecklistCVs> WebcastSpeakerChecklistCVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebcastSpeakerChecklistPresentationFiles> WebcastSpeakerChecklistPresentationFiles { get; set; }
        public virtual WebcastSpeakers WebcastSpeakers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebcastSpeakerConsentForms> WebcastSpeakerConsentForms { get; set; }
    }
}
