//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSUCCMEDataImport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebcastMOCBoards
    {
        public int ID { get; set; }
        public int WebcastID { get; set; }
        public string Board { get; set; }
        public bool IsDeleted { get; set; }
    }
}
